### ISSUE TITLE
[Crash] Minecraft 1.12.2 Crash

### ISSUE THREAD

**Issue by vainlaind4in** [SuperMartijn642/Fusion#11] opened 2023-07-13 19:45 UTC
**Version Info**
- Minecraft, 1.12.2
- Fusion, 1.0.3

**Are you using OptiFine:** Not using Optifine

**Steps to Reproduce**
1. Start up Minecraft with the mods listed in the log
2. A couple seconds after the Minecraft loading screen pops up, it crashes.

Tried starting it with Optifine, however it crashed with the same log.
**Crash report (~/logs/latest.log)**
[latest.log](https://github.com/SuperMartijn642/Fusion/files/12043890/latest.log)

**Comment by SuperMartijn642** [comment] 2023-07-13 21:04
Seems like Fusion and some other mod you have are trying to change the same Minecraft method, leading to a crash.

You are using **a lot** of mods, could you narrow down the mods needed to reproduce the issue?

**Comment by vainlaind4in** [comment] 2023-07-13 22:33
Tried disabling many mods, however I couldn't find the culprit. Though, while I was disabling some mods, it gave a different crash, now having to do something with JEI. The strange thing is, even after reenabling all the mods, it still gave this crash.
[latest.log](https://github.com/SuperMartijn642/Fusion/files/12044881/latest.log)

**Comment by vainlaind4in** [comment] 2023-07-14 15:24
After disabling a bunch of mods and then reenabling them once again, I figured out the culprit. It was VintageFix who is making this crash. 
https://www.curseforge.com/minecraft/mc-mods/vintagefix

**Comment by SuperMartijn642** [comment] 2023-08-19 21:40
Seems both VintageFix and I have added mitigations since you reported this issue, so it should now be fixed by updating either VintageFix or Fusion.
Thank you for reporting the issue!

**Closed as completed by SuperMartijn642** 2023-08-19 21:40 UTC
